// CPAS Branch Report Export
// Generates a styled Excel workbook matching the JAZ Branch Workload schema
// Pulls live data from Supabase cpas_acquisitions and cpas_contract_records

const ExcelJS = require("exceljs");

const SB_URL = process.env.SUPABASE_URL || "https://ylzdfcyiyznazvvbqdam.supabase.co";
const SB_KEY = process.env.SUPABASE_ANON_KEY || "sb_publishable_adMOxPm4Sd5fcUXRf9qKdw_VpwR382c";

const cors = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "Content-Type",
};

// ── Color palette matching the workbook ───────────────────────────
const NAVY   = "FF0B3D91";
const WHITE  = "FFFFFFFF";
const LTBLUE = "FFDBEAFE";
const GOLD   = "FFFEF3C7";
const GREEN  = "FFD1FAE5";
const GRAY   = "FFF1F5F9";
const BORDER_COLOR = "FFCCCCCC";

function headerStyle(bgColor = NAVY, fgColor = WHITE) {
  return {
    font: { bold: true, color: { argb: fgColor }, size: 10, name: "Arial" },
    fill: { type: "pattern", pattern: "solid", fgColor: { argb: bgColor } },
    alignment: { horizontal: "center", vertical: "middle", wrapText: true },
    border: {
      top: { style: "thin", color: { argb: BORDER_COLOR } },
      bottom: { style: "thin", color: { argb: BORDER_COLOR } },
      left: { style: "thin", color: { argb: BORDER_COLOR } },
      right: { style: "thin", color: { argb: BORDER_COLOR } },
    },
  };
}

function dataStyle(bgColor = null) {
  return {
    font: { size: 9, name: "Arial" },
    fill: bgColor ? { type: "pattern", pattern: "solid", fgColor: { argb: bgColor } } : undefined,
    alignment: { vertical: "middle", wrapText: true },
    border: {
      top: { style: "hair", color: { argb: BORDER_COLOR } },
      bottom: { style: "hair", color: { argb: BORDER_COLOR } },
      left: { style: "hair", color: { argb: BORDER_COLOR } },
      right: { style: "hair", color: { argb: BORDER_COLOR } },
    },
  };
}

function applyRowStyle(row, bgColor) {
  row.eachCell({ includeEmpty: true }, cell => {
    Object.assign(cell, { style: dataStyle(bgColor) });
  });
  row.height = 40;
}

async function fetchAcquisitions() {
  const headers = { "apikey": SB_KEY, "Authorization": "Bearer " + SB_KEY };
  const [acqRes, recRes] = await Promise.all([
    fetch(`${SB_URL}/rest/v1/cpas_acquisitions?select=*&order=created_at.desc&limit=500`, { headers }),
    fetch(`${SB_URL}/rest/v1/cpas_contract_records?select=*&order=created_at.desc&limit=500`, { headers }),
  ]);
  const acqs = acqRes.ok ? await acqRes.json() : [];
  const recs = recRes.ok ? await recRes.json() : [];
  return { acqs, recs };
}

exports.handler = async (event) => {
  if (event.httpMethod === "OPTIONS") return { statusCode: 200, headers: cors, body: "" };
  if (event.httpMethod !== "GET" && event.httpMethod !== "POST") {
    return { statusCode: 405, headers: cors, body: "Method Not Allowed" };
  }

  try {
    const { acqs, recs } = await fetchAcquisitions();

    const wb = new ExcelJS.Workbook();
    wb.creator = "CPAS";
    wb.created = new Date();
    wb.calcProperties.fullCalcOnLoad = true;

    // ── Sheet 1: All Contracts ──────────────────────────────────────
    const ws = wb.addWorksheet("All Contracts", {
      views: [{ state: "frozen", ySplit: 3 }],
      pageSetup: { orientation: "landscape", fitToPage: true, fitToWidth: 1 },
    });

    // Title rows
    ws.mergeCells("A1:AD1");
    const titleCell = ws.getCell("A1");
    titleCell.value = "JAZ BRANCH WORKLOAD REPORT — ALL CONTRACTS";
    Object.assign(titleCell, {
      font: { bold: true, size: 12, color: { argb: WHITE }, name: "Arial" },
      fill: { type: "pattern", pattern: "solid", fgColor: { argb: NAVY } },
      alignment: { horizontal: "center", vertical: "middle" },
    });
    ws.getRow(1).height = 24;

    ws.mergeCells("A2:AD2");
    const subtitleCell = ws.getCell("A2");
    subtitleCell.value = "NASA ARC | Research Centers Office of Procurement | JAZ Branch  ·  Generated by CPAS " + new Date().toLocaleDateString("en-US");
    Object.assign(subtitleCell, {
      font: { italic: true, size: 9, color: { argb: NAVY }, name: "Arial" },
      fill: { type: "pattern", pattern: "solid", fgColor: { argb: LTBLUE } },
      alignment: { horizontal: "center", vertical: "middle" },
    });
    ws.getRow(2).height = 18;

    // Column headers — matching workbook exactly
    const COLS = [
      { key: "co_name",           header: "Assigned CO/CS",         width: 18 },
      { key: "status",            header: "Status",                  width: 12 },
      { key: "priority",          header: "Priority",                width: 10 },
      { key: "contract_number",   header: "Contract Number",         width: 20 },
      { key: "rfp_number",        header: "RFP/NRA Number",          width: 18 },
      { key: "pr_number",         header: "PR Number / Amount",      width: 16 },
      { key: "contractor_name",   header: "Contractor Name",         width: 22 },
      { key: "contract_type",     header: "Contract Type",           width: 12 },
      { key: "description",       header: "Description",             width: 35 },
      { key: "cor_name",          header: "COR",                     width: 18 },
      { key: "support_code",      header: "Support Code",            width: 12 },
      { key: "directorate",       header: "Directorate",             width: 14 },
      { key: "primary_funding",   header: "Primary Funding",         width: 14 },
      { key: "competition",       header: "Sole Source or Competitive", width: 14 },
      { key: "pop_start",         header: "POP Start",               width: 12 },
      { key: "pop_end",           header: "POP End",                 width: 12 },
      { key: "current_value",     header: "Current Value",           width: 16 },
      { key: "potential_value",   header: "Potential Value (Base+Options)", width: 18 },
      { key: "current_funding",   header: "Current Funding",         width: 16 },
      { key: "fund_thru_date",    header: "Fund-Thru Date",          width: 12 },
      { key: "current_period",    header: "Current Period",          width: 18 },
      { key: "closeout_submitted",header: "Closeout Submitted?",     width: 12 },
      { key: "over_10m",          header: "Over $10M (Admin DC)",    width: 12 },
      { key: "is_nra",            header: "NRA?",                    width: 8  },
      { key: "impact_statement",  header: "Impact Statement",        width: 40 },
      { key: "pending_actions",   header: "Pending Actions / Status Notes", width: 35 },
      { key: "near_file_link",    header: "Link to Award File",      width: 20 },
    ];

    ws.columns = COLS.map((c, i) => ({
      key: c.key, width: c.width,
    }));

    const headerRow = ws.getRow(3);
    COLS.forEach((col, i) => {
      const cell = headerRow.getCell(i + 1);
      cell.value = col.header;
      Object.assign(cell, headerStyle(NAVY, WHITE));
    });
    headerRow.height = 42;

    // Data rows — merge acquisitions + contract records
    const merged = new Map();

    // Start with contract records (have contractor name, contract number)
    for (const r of recs) {
      const key = r.id;
      merged.set(key, {
        co_name: r.co_name || "",
        status: r.status || "Pre-Award",
        priority: r.priority || "",
        contract_number: r.contract_number || "",
        rfp_number: r.rfp_number || r.solicitation_number || "",
        pr_number: "",
        contractor_name: r.contractor_name || "",
        contract_type: r.contract_type || "",
        description: r.description || r.title || "",
        cor_name: r.cor_name || "",
        support_code: r.support_code || "",
        directorate: r.directorate || "",
        primary_funding: r.primary_funding || "",
        competition: r.competition || "",
        pop_start: r.pop_start ? new Date(r.pop_start) : "",
        pop_end: r.pop_end ? new Date(r.pop_end) : "",
        current_value: parseFloat(r.current_value || r.value) || "",
        potential_value: parseFloat(r.potential_value) || "",
        current_funding: parseFloat(r.current_funding) || "",
        fund_thru_date: r.fund_thru_date ? new Date(r.fund_thru_date) : "",
        current_period: r.current_period || "",
        closeout_submitted: r.closeout_submitted ? "Yes" : "",
        over_10m: (parseFloat(r.current_value || r.value) >= 10000000) ? "Yes" : "",
        is_nra: r.is_nra ? "Yes" : "",
        impact_statement: r.impact_statement || "",
        pending_actions: r.pending_actions || "",
        near_file_link: r.near_file_link || "",
        _source: "record",
      });
    }

    // Fill in from acquisitions where records may be missing
    for (const a of acqs) {
      const intake = a.intake_data || {};
      const key = "acq_" + a.id;
      if (!merged.has(key)) {
        merged.set(key, {
          co_name: a.co_name || intake.coName || "",
          status: a.status || "Draft",
          priority: a.priority || "",
          contract_number: a.contract_number || "",
          rfp_number: "",
          pr_number: "",
          contractor_name: a.contractor_name || "",
          contract_type: a.contract_type || intake.contractType || "",
          description: a.title || intake.reqTitle || "",
          cor_name: a.cor_name || intake.techRepName || "",
          support_code: a.support_code || "",
          directorate: a.directorate || "",
          primary_funding: a.primary_funding || "",
          competition: (a.competition || intake.competitionStrategy || "").replace(/_/g," "),
          pop_start: "",
          pop_end: "",
          current_value: parseFloat(a.value || intake.value) || "",
          potential_value: "",
          current_funding: "",
          fund_thru_date: "",
          current_period: intake.pop || "",
          closeout_submitted: "",
          over_10m: (parseFloat(a.value || intake.value) >= 10000000) ? "Yes" : "",
          is_nra: "",
          impact_statement: "",
          pending_actions: "",
          near_file_link: "",
          _source: "acquisition",
        });
      }
    }

    let rowNum = 4;
    for (const [, row] of merged) {
      const wsRow = ws.getRow(rowNum);
      COLS.forEach((col, i) => {
        const cell = wsRow.getCell(i + 1);
        const val = row[col.key];
        cell.value = val;
        // Format currency cells
        if (["current_value","potential_value","current_funding"].includes(col.key) && typeof val === "number") {
          cell.numFmt = "$#,##0";
        }
        // Format date cells
        if (["pop_start","pop_end","fund_thru_date"].includes(col.key) && val instanceof Date) {
          cell.numFmt = "mm/dd/yyyy";
        }
        // Status color coding
        const bgColor = (row.status === "Post-Award") ? null :
                        (row.status === "Pre-Award") ? GOLD :
                        (row.status === "Closeout") ? GREEN : GRAY;
        Object.assign(cell, dataStyle(bgColor));
      });
      wsRow.height = 40;
      rowNum++;
    }

    // Auto-filter on header row
    ws.autoFilter = { from: { row: 3, column: 1 }, to: { row: 3, column: COLS.length } };

    // ── Sheet 2: Dashboard ─────────────────────────────────────────
    const dash = wb.addWorksheet("Dashboard");

    const dashTitle = dash.getCell("B1");
    dashTitle.value = "JAZ BRANCH WORKLOAD DASHBOARD";
    Object.assign(dashTitle, headerStyle(NAVY, WHITE));
    dash.mergeCells("B1:N1");
    dash.getRow(1).height = 28;

    const agencyCell = dash.getCell("H1");
    agencyCell.value = "NASA ARC - Research Centers Office of Procurement";

    // Portfolio Status section
    const dashHeaders = ["PRE-AWARD","POST-AWARD","CLOSEOUT","CANCELLED","TOTAL","","ACTIVE VALUE","POTENTIAL VALUE","OBLIGATED","OVER $10M","NRA","TRANSFERRED"];
    ["B","C","D","E","F","G","H","I","J","K","L","M"].forEach((col, i) => {
      const c = dash.getCell(col + "3");
      c.value = dashHeaders[i];
      Object.assign(c, headerStyle(LTBLUE, NAVY));
    });

    // Formula row pulling from All Contracts sheet
    const formulas = [
      `=COUNTIF('All Contracts'!B:B,"Pre-Award")`,
      `=COUNTIF('All Contracts'!B:B,"Post-Award")`,
      `=COUNTIF('All Contracts'!B:B,"Closeout")`,
      `=COUNTIF('All Contracts'!B:B,"Cancelled")`,
      `=COUNTA('All Contracts'!B4:B5000)`,
      "",
      `=SUMPRODUCT(('All Contracts'!B4:B5000="Post-Award")*IFERROR('All Contracts'!Q4:Q5000,0))`,
      `=SUMPRODUCT(('All Contracts'!B4:B5000="Post-Award")*IFERROR('All Contracts'!R4:R5000,0))`,
      `=SUMPRODUCT(('All Contracts'!B4:B5000="Post-Award")*IFERROR('All Contracts'!S4:S5000,0))`,
      `=COUNTIF('All Contracts'!W:W,"Yes")`,
      `=COUNTIF('All Contracts'!X:X,"Yes")`,
      `=COUNTIF('All Contracts'!B:B,"Transferred")`,
    ];
    ["B","C","D","E","F","G","H","I","J","K","L","M"].forEach((col, i) => {
      const c = dash.getCell(col + "4");
      if (formulas[i]) c.value = { formula: formulas[i] };
      if (["H","I","J"].includes(col)) c.numFmt = "$#,##0";
      Object.assign(c, dataStyle());
    });
    dash.getRow(4).height = 24;

    // Column widths
    ["B","C","D","E","F","H","I","J","K","L","M"].forEach(col => {
      dash.getColumn(col).width = 16;
    });

    // ── Sheet 3: Lookups (controlled vocabulary) ───────────────────
    const look = wb.addWorksheet("Lookups");
    const lookData = {
      A: ["CO/CS Names", ...acqs.map(a => a.co_name || "").filter(Boolean).filter((v,i,arr) => arr.indexOf(v)===i).slice(0,30)],
      B: ["Status", "Pre-Award", "Post-Award", "Closeout", "Cancelled", "Transferred"],
      C: ["Priority", "High", "Medium", "Low"],
      D: ["Contract Type", "FFP", "CPFF", "CPAF", "CPIF", "CP No Fee", "T&M", "LH", "HYBRID", "IDIQ"],
      E: ["Competitive?", "Sole Source", "Competitive", "IDIQ (Single Award)", "IDIQ (Multiple Award)", "TBD"],
      F: ["Support Code", "PX", "RE", "RS", "RD", "R", "SG", "HQ"],
      G: ["Directorate", "S", "R", "P", "T", "D", "HQ", "TBD"],
      H: ["Primary Funding", "SMD", "STMD", "ARMD", "SCMD", "SOMD", "SSMS", "BARDA"],
      I: ["Yes/No", "Yes", "No"],
    };

    Object.entries(lookData).forEach(([col, values]) => {
      values.forEach((v, i) => {
        const c = look.getCell(col + (i + 1));
        c.value = v;
        if (i === 0) Object.assign(c, headerStyle(NAVY, WHITE));
        else Object.assign(c, dataStyle());
      });
      look.getColumn(col).width = 20;
    });

    // ── Serialize to buffer ────────────────────────────────────────
    const buf = await wb.xlsx.writeBuffer();
    const b64 = Buffer.from(buf).toString("base64");

    const filename = "CPAS_Branch_Report_" + new Date().toISOString().slice(0,10) + ".xlsx";

    return {
      statusCode: 200,
      headers: {
        ...cors,
        "Content-Type": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        "Content-Disposition": `attachment; filename="${filename}"`,
        "Content-Transfer-Encoding": "base64",
      },
      body: b64,
      isBase64Encoded: true,
    };

  } catch (err) {
    console.error("export-report error:", err);
    return {
      statusCode: 500,
      headers: { ...cors, "Content-Type": "application/json" },
      body: JSON.stringify({ error: err.message }),
    };
  }
};
